
DROP TABLE if EXISTS customers CASCADE;
DROP SEQUENCE IF EXISTS customers_id_seq;
CREATE TABLE customers
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY,
    address  varchar(80) not null,
    city     varchar(40) not null,
    name     varchar(100) not null,
    zip_code varchar(8),
    PRIMARY KEY (id)
);

DROP TABLE if EXISTS orderitems CASCADE;
CREATE TABLE orderitems
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    quantity      integer NOT NULL,
    selling_price double  NOT NULL,
    order_id      bigint,
    product_id    bigint,
    PRIMARY KEY (id)
);

DROP TABLE if EXISTS orders CASCADE;
CREATE TABLE orders
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    date          date,
    shipped       boolean NOT NULL,
    shipping_date date,
    buyer_id      bigint,
    seller_id     bigint,
    PRIMARY KEY (id)
);

DROP TABLE if EXISTS products CASCADE;
CREATE TABLE products
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(100) not null,
    ean_code    varchar(13),
    price       double NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE orderitems
    ADD CONSTRAINT FK_orderitem_order FOREIGN KEY (order_id) REFERENCES orders;

ALTER TABLE orderitems
    ADD CONSTRAINT FK FOREIGN KEY (product_id) REFERENCES products;

ALTER TABLE orders
    ADD CONSTRAINT FK_orderitem_buyer FOREIGN KEY (buyer_id) REFERENCES customers;

ALTER TABLE orders
    ADD CONSTRAINT FK_orderitem_seller FOREIGN KEY (seller_id) REFERENCES customers;